### ISSUE TITLE
Validation messages doesn't work

### ISSUE THREAD

**Issue by angelcamo1234** [ArielMejiaDev/json-api-auth#1]
Hi,

When i use '/api/register' with out 'Fields required', just can i see this

![image](https://user-images.githubusercontent.com/36573891/111396836-e7a82800-868d-11eb-932a-d778194e89d2.png)

![image](https://user-images.githubusercontent.com/36573891/111396897-04446000-868e-11eb-8bf1-38be69da7ff7.png)

**Comment by ArielMejiaDev** [comment]
You need to set on Postman headers `Accept` `application/json`, `Content-type` `application/json`

with this Laravel would automatically identify the request response and return validation errors as json, instead of returning a redirect response.
