### ISSUE TITLE
Forgot Password API won't send email and return error when I enter email that is not in database

### ISSUE THREAD

**Issue by ben1234456** [ArielMejiaDev/json-api-auth#2]
I'm using react native as my front-end this is my code to fetch the API:
![image](https://user-images.githubusercontent.com/62086516/134763015-df4584e3-8607-412f-a751-e924c5621978.png)
If I enter an email that exist in the database:
![image](https://user-images.githubusercontent.com/62086516/134763050-79893ab1-af0f-46ac-ba6a-3dadf836308d.png)

It return me a sent email message but there is nothing in the email entered

If I enter an email that does not exist in the database:
![image](https://user-images.githubusercontent.com/62086516/134763059-232faa21-0dbb-4eb2-8fdb-17c27e0c1a13.png)

Any ideas?

**Comment by ArielMejiaDev** [comment]
Hi @ben1234456 it is already solved by the new release: https://github.com/ArielMejiaDev/json-api-auth/compare/1.0.3...1.0.4

basically, it needs to validate first that the email really exists in the user's table database, hope it is useful.
