### ISSUE TITLE
Update laravel 9

### ISSUE THREAD

**Issue by alex9310** [ArielMejiaDev/json-api-auth#3]
how to update this library for laravel 9?

**Comment by pjhile** [comment]
I've got a PR in for this if you want to check it out: https://github.com/ArielMejiaDev/json-api-auth/pull/5

**Comment by ArielMejiaDev** [comment]
Thanks @pjhile 💯

**Comment by jalmirante** [comment]
@ArielMejiaDev  when update to laravel 9, thanks.

**Comment by ArielMejiaDev** [comment]
@jalmirante I think that is already added support for L9
